### ISSUE TITLE
Nodemon, add it!

### ISSUE THREAD

**Issue by michaeljonathanblack** [wordstosong/jacobscript#20]
https://www.npmjs.com/package/nodemon

https://github.com/remy/nodemon

**Comment by wordstosong** [comment]
So I installed Nodemon globally (the general install) and locally, but I wasn't sure if locally was the right call. And I'm not having luck in *using* it, so... let's address this when we ScreenHero next.

**Comment by wordstosong** [comment]
We did this thing, even though I can't say I'm entirely sure I recall everything that was talked about at 3am, but that's okay!
