### ISSUE TITLE
Feature Request: Styles

### ISSUE THREAD

**Issue by michaeljonathanblack** [wordstosong/jacobscript#4]
Maybe implement some sort of design document around pieces of the site, e.g. fonts, colors, header, footer, body. And then add styles to the site.

**Comment by wordstosong** [comment]
Not quite fulfilling this ticket/issue, but here are the comps I have been working on the past week or so. Will start including defined design features. 

Full desktop version
![desktop](https://cloud.githubusercontent.com/assets/24365400/23634352/6f88fa7e-028f-11e7-9bf8-c7d54735d2cf.jpg)

Mid-break version
![mid-break](https://cloud.githubusercontent.com/assets/24365400/23634354/6f897d28-028f-11e7-85db-f95bcc136b0e.jpg)

Mobile version
![mobile-1](https://cloud.githubusercontent.com/assets/24365400/23634355/6f89be32-028f-11e7-8051-5eb6742896b1.jpg)
![mobile-2-v1](https://cloud.githubusercontent.com/assets/24365400/23634356/6f89e59c-028f-11e7-9977-1cf57163fc12.jpg)
![mobile-2-v2](https://cloud.githubusercontent.com/assets/24365400/23634353/6f894bdc-028f-11e7-8458-601b5ce96f28.jpg)
![mobile-3](https://cloud.githubusercontent.com/assets/24365400/23634357/6f8a1a76-028f-11e7-84f5-a6ba88384d3d.jpg)

**Comment by michaeljonathanblack** [comment]
Awesome! This looks like a solid starting point. If you can break individual assets out into their component parts, it should be easy to start stitching up a website, e.g.

logo.png
logo-small.png
first-icon, previous-icon, next-icon, last-icon.png
facebook-control-icon, share-control-icon, twitter-control-icon.png
facebook-header-icon, tumbler-header-icon, twitter-header-icon.png
mobile-menu-icon.png

Something like that. And if you can make the icons `svg` that'd be even better (it looks like they'd be reusable from header to control, then).

**Comment by michaeljonathanblack** [comment]
It seems like this ticket is basically there! What do you feel remains @wordstosong or can we close this?

**Comment by wordstosong** [comment]
I think we can close this as it is now. So I'll do that.
