### ISSUE TITLE
Feature Request: Header and Footer

### ISSUE THREAD

**Issue by michaeljonathanblack** [wordstosong/jacobscript#5]
With links to inevitable interior pages.

**Comment by michaeljonathanblack** [comment]
It seems like this ticket is a footer away from being complete, unless you feel like the footer is all that it needs to be for now? @wordstosong

**Comment by michaeljonathanblack** [comment]
@wordstosong ?

**Comment by wordstosong** [comment]
Added very basic footer text -- adequate?

**Comment by michaeljonathanblack** [comment]
Seems good!
